version: '3'


services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: mentorshow--parse-postgres-db
    restart: always
    networks:
      - back
    ports:
      - "50000:5432"
    env_file:
      - .env
    volumes:
      - ./data/postgres:/bitnami/postgresql

  api:
    build: ./parse-server
    image: kelyo/parse-server
    container_name: mentorshow-parse-server
    restart: always
    command: nodemon --exec npm run dev
    links:
      - postgres:postgres
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - front
      - back
    volumes:
      - ./parse-server:/usr/src/parse
    labels:
      traefik.enable: "true"
      traefik.port: "1337"
      traefik.frontend.rule: "Host:${APP_DOMAIN}"
      traefik.docker.network: "${FRONT_NETWORK}"

networks:
  front:
    external:
      name: ${FRONT_NETWORK}
  back:
    driver: bridge
